import {StyleSheet} from 'react-native';


export default StyleSheet.create({
    container:{
        flexGrow:1,
        maxHeight:'100%'
    },
    content:{
        paddingHorizontal:10,
        paddingVertical:20
    },
    footerContainer:{
        flexGrow:1,
        maxHeight:'100%',
        alignContent:'flex-end',
        justifyContent:'flex-end',
    },
    field:{
        flexDirection:'row',
        alignItems:'center',
        marginBottom:20
    },
    input:{
        flexGrow:1,
    },
    buttonContainer:{
        alignItems:'center',
        marginTop:20,
    },
    spinnerContainer:{
        alignItems:'center',
        marginTop:140,
    },
    button:{
        width:200,
        borderColor:'#027691',
        borderWidth:2,
        height:50,
        alignItems:'center',
        justifyContent:'center',
        borderRadius:25,
    },
    buttonText:{
        fontWeight:'bold',
        fontSize:18,
        color:'#027691',
    },
    signUpLink:{
        alignItems:'center',
        marginTop:10,
    },
});